
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 50242
 */
public class jfrmPiezasCompu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmPiezasCompu.class.getName());

    /**
     * Creates new form Menu_Imagenes
     */
    public jfrmPiezasCompu() {
        initComponents();
        this.setTitle("MotherBoard");    
        this.setSize(500, 450);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblPiezas = new javax.swing.JLabel();
        jlblNomPieza = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlbltexto = new javax.swing.JLabel();
        jlbltexto2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPlacaBase = new javax.swing.JMenuItem();
        itemProcesador = new javax.swing.JMenuItem();
        itemMemoria = new javax.swing.JMenuItem();
        itemCooler = new javax.swing.JMenuItem();
        itemFuentePoder = new javax.swing.JMenuItem();
        itemDiscoduro = new javax.swing.JMenuItem();
        itemUnidadssd = new javax.swing.JMenuItem();
        itemTarjetaVideo = new javax.swing.JMenuItem();
        itemTarjetaRed = new javax.swing.JMenuItem();
        itemVentilador = new javax.swing.JMenuItem();
        itemSonido = new javax.swing.JMenuItem();
        itemCMOS = new javax.swing.JMenuItem();
        itemSata = new javax.swing.JMenuItem();
        itemAlimentacion = new javax.swing.JMenuItem();
        itemBiosUefi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblNomPieza.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jlblNomPieza.setForeground(new java.awt.Color(0, 0, 0));
        jlblNomPieza.setText("Piezas del ordenador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        jlbltexto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jlbltexto.setText("Concepto:");

        jlbltexto2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jlbltexto2.setText("Función:");

        jMenu1.setMnemonic('A');
        jMenu1.setText("Archivo");

        itemAbrir.setMnemonic('A');
        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(this::itemAbrirActionPerformed);
        jMenu1.add(itemAbrir);

        itemGuardar.setMnemonic('G');
        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(this::itemGuardarActionPerformed);
        jMenu1.add(itemGuardar);

        itemSalir.setMnemonic('S');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('C');
        jMenu2.setText("Imagenes");

        itemPlacaBase.setText("Placa Base");
        itemPlacaBase.addActionListener(this::itemPlacaBaseActionPerformed);
        jMenu2.add(itemPlacaBase);

        itemProcesador.setText("Procesador");
        itemProcesador.addActionListener(this::itemProcesadorActionPerformed);
        jMenu2.add(itemProcesador);

        itemMemoria.setText("Memoria RAM");
        itemMemoria.addActionListener(this::itemMemoriaActionPerformed);
        jMenu2.add(itemMemoria);

        itemCooler.setText("Cooler");
        itemCooler.addActionListener(this::itemCoolerActionPerformed);
        jMenu2.add(itemCooler);

        itemFuentePoder.setText("Fuente de Poder");
        itemFuentePoder.addActionListener(this::itemFuentePoderActionPerformed);
        jMenu2.add(itemFuentePoder);

        itemDiscoduro.setText("Disco Duro (HDD)");
        itemDiscoduro.addActionListener(this::itemDiscoduroActionPerformed);
        jMenu2.add(itemDiscoduro);

        itemUnidadssd.setText("Unidad SSD");
        itemUnidadssd.addActionListener(this::itemUnidadssdActionPerformed);
        jMenu2.add(itemUnidadssd);

        itemTarjetaVideo.setText("Tarjeta de Video (GPU)");
        itemTarjetaVideo.addActionListener(this::itemTarjetaVideoActionPerformed);
        jMenu2.add(itemTarjetaVideo);

        itemTarjetaRed.setText("Tarjeta de Red");
        itemTarjetaRed.addActionListener(this::itemTarjetaRedActionPerformed);
        jMenu2.add(itemTarjetaRed);

        itemVentilador.setText("Ventilador del Gabinete");
        itemVentilador.addActionListener(this::itemVentiladorActionPerformed);
        jMenu2.add(itemVentilador);

        itemSonido.setText("Tarjeta de Sonido");
        itemSonido.addActionListener(this::itemSonidoActionPerformed);
        jMenu2.add(itemSonido);

        itemCMOS.setText("Bateria CMOS");
        itemCMOS.addActionListener(this::itemCMOSActionPerformed);
        jMenu2.add(itemCMOS);

        itemSata.setText("Cable SATA");
        itemSata.addActionListener(this::itemSataActionPerformed);
        jMenu2.add(itemSata);

        itemAlimentacion.setText("Cable de Alimentacion");
        itemAlimentacion.addActionListener(this::itemAlimentacionActionPerformed);
        jMenu2.add(itemAlimentacion);

        itemBiosUefi.setText("BIOS/UEFI");
        itemBiosUefi.addActionListener(this::itemBiosUefiActionPerformed);
        jMenu2.add(itemBiosUefi);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('A');
        jMenu3.setText("Ayuda");

        itemCreditos.setText("Creditos");
        itemCreditos.addActionListener(this::itemCreditosActionPerformed);
        jMenu3.add(itemCreditos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jlblPiezas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addComponent(jlblNomPieza)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbltexto2)
                                    .addComponent(jlbltexto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblNomPieza)
                        .addGap(18, 18, 18)
                        .addComponent(jlbltexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbltexto2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblPiezas)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
        int pablo=JOptionPane.showConfirmDialog(null, "Desea Salir del Software??");
        if(pablo==0)
            System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMemoriaActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Memoria RAM");
        jlblNomPieza.setForeground(Color.blue);
        jlbltexto.setText("Concepto: Memoria ultra rápida y temporal.");
        jlbltexto2.setText("Función Principal: Guardar datos del momento para acceso rápido.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/ram.png")));
    }//GEN-LAST:event_itemMemoriaActionPerformed

    private void itemPlacaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPlacaBaseActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("MotherBoard");
        jlblNomPieza.setForeground(Color.gray);
        jlbltexto.setText("Concepto: Tarjeta de circuitos principal de la PC.");
        jlbltexto2.setText("Función Principal: Conectar y comunicar todas las piezas.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/motherboard.png")));
        
        
        
    }//GEN-LAST:event_itemPlacaBaseActionPerformed

    private void itemProcesadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProcesadorActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.black);
        jlbltexto.setText("Concepto: El chip cerebro del ordenador.");
        jlbltexto2.setText("Función Principal: Procesar los datos y ejecutar programas.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/cpu.png")));
    }//GEN-LAST:event_itemProcesadorActionPerformed

    private void itemCoolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCoolerActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Cooler");
        jlblNomPieza.setForeground(Color.black);
        jlbltexto.setText("Concepto: Disipador con ventilador sobre la CPU.");
        jlbltexto2.setText("Función Principal: Enfriar el procesador para evitar daños.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/cooler.png")));
    }//GEN-LAST:event_itemCoolerActionPerformed

    private void itemFuentePoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuentePoderActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Fuente de Poder");
        jlblNomPieza.setForeground(Color.pink);
        jlbltexto.setText("Concepto: Convertidor de energía eléctrica.");
        jlbltexto2.setText("Función Principal: Dar energía regulada a todos los componentes.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/fuente.png")));
    }//GEN-LAST:event_itemFuentePoderActionPerformed

    private void itemDiscoduroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDiscoduroActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Disco Duro");
        jlblNomPieza.setForeground(Color.orange);
        jlbltexto.setText("Concepto: Almacenamiento magnético con discos.");
        jlbltexto2.setText("Función Principal: Guardar archivos pesados de forma lenta pero barata.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/discoduro2.png")));
    }//GEN-LAST:event_itemDiscoduroActionPerformed

    private void itemUnidadssdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUnidadssdActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Unidad SSD");
        jlblNomPieza.setForeground(Color.pink);
        jlbltexto.setText("Concepto: Almacenamiento moderno con chips.");
        jlbltexto2.setText("Función Principal: Iniciar el sistema y abrir archivos al instante.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/unidadssd.png")));
    }//GEN-LAST:event_itemUnidadssdActionPerformed

    private void itemTarjetaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTarjetaVideoActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Tarjeta de Video (GPU)");
        jlblNomPieza.setForeground(Color.blue);
        jlbltexto.setText("Concepto: Procesador especializado en imágenes.");
        jlbltexto2.setText("Función Principal: Renderizar y mostrar gráficos en la pantalla.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/tarjetavideo.png")));
        
    }//GEN-LAST:event_itemTarjetaVideoActionPerformed

    private void itemTarjetaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTarjetaRedActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Tarjeta de Red");
        jlblNomPieza.setForeground(Color.black);
        jlbltexto.setText("Concepto: Chip o tarjeta de conexión.");
        jlbltexto2.setText("Función Principal: Conectar la PC a internet (cable o Wi-Fi).");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/tarjetared2.png")));
    }//GEN-LAST:event_itemTarjetaRedActionPerformed

    private void itemVentiladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentiladorActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Ventilador del Gabinete");
        jlblNomPieza.setForeground(Color.gray);
        jlbltexto.setText("Concepto: Extractor de aire en la carcasa.");
        jlbltexto2.setText("Función Principal: Hacer circular aire fresco dentro del gabinete.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/ventilador2.png")));
    }//GEN-LAST:event_itemVentiladorActionPerformed

    private void itemSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSonidoActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Tarjeta de Sonido");
        jlblNomPieza.setForeground(Color.orange);
        jlbltexto.setText("Concepto: Chip procesador de audio.");
        jlbltexto2.setText("Función Principal: Controlar la salida de audio y entrada de micrófono.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/tarjetasonido.png")));
    }//GEN-LAST:event_itemSonidoActionPerformed

    private void itemCMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCMOSActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Bateria CMOS");
        jlblNomPieza.setForeground(Color.pink);
        jlbltexto.setText("Concepto: Pila de reloj de la placa base.");
        jlbltexto2.setText("Función Principal: Mantener la hora, fecha y ajustes de la BIOS.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/bateriacmos2.png")));
    }//GEN-LAST:event_itemCMOSActionPerformed

    private void itemSataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSataActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Cable SATA");
        jlblNomPieza.setForeground(Color.blue);
        jlbltexto.setText("Concepto: Cable de datos plano interno.");
        jlbltexto2.setText("Función Principal: Conectar discos y SSDs con la placa base.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/cablesata2.png")));
    }//GEN-LAST:event_itemSataActionPerformed

    private void itemAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentacionActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("Cable de Alimentacion");
        jlblNomPieza.setForeground(Color.black);
        jlbltexto.setText("Concepto: Cable eléctrico externo de pared.");
        jlbltexto2.setText("Función Principal: Llevar electricidad desde el enchufe a la fuente.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/cablealimentacion2.png")));
    }//GEN-LAST:event_itemAlimentacionActionPerformed

    private void itemBiosUefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBiosUefiActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblNomPieza.setText("BIOS/UEFI");
        jlblNomPieza.setForeground(Color.gray);
        jlbltexto.setText("Concepto: El primer software que arranca la PC.");
        jlbltexto2.setText("Función Principal: Revisar el hardware antes de cargar el sistema.");
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A/Guiaimagenes/biosuefi2.png")));
    }//GEN-LAST:event_itemBiosUefiActionPerformed

    private void itemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreditosActionPerformed
        JOptionPane.showMessageDialog(this, "Creditos del programa a:\n"
                + "Santiago Turcios Herrera\n"
                + "Clave: 30\n"
                + "IV-D\n");
    }//GEN-LAST:event_itemCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmPiezasCompu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAlimentacion;
    private javax.swing.JMenuItem itemBiosUefi;
    private javax.swing.JMenuItem itemCMOS;
    private javax.swing.JMenuItem itemCooler;
    private javax.swing.JMenuItem itemCreditos;
    private javax.swing.JMenuItem itemDiscoduro;
    private javax.swing.JMenuItem itemFuentePoder;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemMemoria;
    private javax.swing.JMenuItem itemPlacaBase;
    private javax.swing.JMenuItem itemProcesador;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSata;
    private javax.swing.JMenuItem itemSonido;
    private javax.swing.JMenuItem itemTarjetaRed;
    private javax.swing.JMenuItem itemTarjetaVideo;
    private javax.swing.JMenuItem itemUnidadssd;
    private javax.swing.JMenuItem itemVentilador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPiezas;
    private javax.swing.JLabel jlbltexto;
    private javax.swing.JLabel jlbltexto2;
    // End of variables declaration//GEN-END:variables
}
